### ISSUE TITLE
problem with the character * (star) when doing a conversion from xml to json 

### ISSUE THREAD

**Issue by cjo4github** [engswee/com.equalize.xpi.af.modules#12] opened 2019-02-01 12:12 UTC
Hi Eng Swee

We think we have problem with the character * (star) when doing a conversion from xml to json using XML2JSONConverter.
It looks like that * is being lost during the xml-json-conversion. However this only applies to
the special case, when * is in a XML tag. As soon as there are more characters, like “* XX” the conversion is correct:

![image](https://user-images.githubusercontent.com/44255361/52122369-0caebd80-2623-11e9-9e91-8ab60caae6d6.png)

Do you you know this problem or how to solve our problem (be file or JMS receiver adapter) in connection with the use of FormatConversionBean?

Thanks for your feedback and kind regards
Christof

**Comment by engswee** [comment] 2019-02-04 07:39
Hi Christof

Thanks for logging this issue.

I currently do not have access to a PI system, as well as my own NWDS setup, so I'm unable to test this both on the server or locally.

Instead I tried this "star" character using the CPI version of FormatConversionBean and it worked fine there. There is not much change in terms of logic between the PI version when I ported it to CPI.

Can you please try to see if this issue can be reproduced if you test it using NWDS on your local machine?

Can you also attach a sample of the input XML payload here that is causing the issue? I'd like to try it further on CPI.

Regards
Eng Swee

**Comment by cjo4github** [comment] 2019-02-04 09:10
Hello Eng Swee

Thanks for your feedback.

Sorry, I've never worked with CPI so far.
As far as I know you need to have a CPI in order
to use it: https://blogs.sap.com/2018/09/04/formatconversionbean-arrives-in-cpi/
We only have an on premise PI system.
I'm not sure on how to reproduce the error using NWDS (eclispe) on
my local machine using the CPI version of the FormatConversionBean, if I understood
you well.

Attached you find a sample xml input and json output of the example described.

Thanks for your feedback.

Kind regards
Christof





[CLFMAS.zip](https://github.com/engswee/equalize-xpi-modules/files/2827174/CLFMAS.zip)

**Comment by engswee** [comment] 2019-02-04 09:48
Hi Christof

I meant try to reproduce it on NWDS using the PI version instead of testing directly on the PI server.

Regards
Eng Swee


________________________________

**Comment by cjo4github** [comment] 2019-02-04 16:04
Hi Eng Swee

I'm really sorry but I do not understand how you exaclty mean how to reproduce it on NWDS using the PI version. Maybe you can explain it more in detail or I wait until you can test it?
Kind regards Christof

**Comment by engswee** [comment] 2019-02-05 06:34
Hi Christof

I tried testing using your file but the * character is converted fine in the JSON output - see below:-

![image](https://user-images.githubusercontent.com/7220623/52256540-02a5fb00-2952-11e9-8c88-ea39985f8976.png)

I'd suggest you try to test locally on your own local NWDS setup (if possible) as I mentioned earlier. To do that, you first have to clone this repository, and 
https://github.com/engswee/equalize-xpi-tester repository into your local machine, then import the projects into NWDS.

My blog https://blogs.sap.com/2016/01/22/setup-comequalizexpiafmodules-adapter-module-project-in-nwds-easily-using-egit/ should provide you further details on how to set it up if you haven't done so.

Testing can be done by running [ModuleTesterMain.java](https://github.com/engswee/equalize-xpi-tester/blob/master/com.equalize.xpi.tester/src/com/equalize/xpi/af/modules/tester/ModuleTesterMain.java) from the equalise-xpi-tester repository by providing the correct arguments (sample in the code itself). You will need to set up the tester project build dependency such that it can access the other projects of the main repository.

Regards
Eng Swee

**Comment by cjo4github** [comment] 2019-02-15 15:02
Hello Eng Swee

thanks for you input regarding NWDS and the link provided.
You're right, on the own local NWDS the error does not occur,
but it occurs on the PI why this is, I don't know (using V 1.7.0 
of com.equalize.xpi.af.modules.app). Do you have an idea why?

However in the mean time I've deployed V1.7.1 and now it works
on the PI as well...strange.
Anyhow thanks for your precious support.

Kind regards
Christof

**Comment by engswee** [comment] 2019-02-17 06:53
Hi Christof

Thanks for confirming that 1.7.1 solved the issue.

Not too sure why 1.7.0 did not work on your PI server. Main changes in 1.7.1 was related to the previous encoding issue that you highlighted and also a change on how the XML is parsed. Maybe one of these two could have been the issue... or maybe not - can't tell unless I can consistently reproduce the issue on my end.

Anyway, since it's fine now, I'm proceeding to close the issue.

If you come across anything else in the future, do open another issue and I'll see how I can assist.

**Closed as completed by engswee** 2019-02-17 06:53 UTC
